# Generated by Django 5.0.1 on 2024-02-18 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketsystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='stripe',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ticketsystem.stripeaccount'),
        ),
    ]
