# Generated by Django 5.0.1 on 2024-02-20 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketsystem', '0002_alter_club_stripe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='event',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ticketsystem.event'),
        ),
    ]
