# Generated by Django 5.0.1 on 2024-03-01 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketsystem', '0006_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('PUB', 'Public'), ('PRI', 'Private'), ('CLO', 'Closed')], default='PUB', max_length=3),
        ),
    ]
